---
format:
  html:
    toc: true
    toc-depth: 4
    page-layout: full
    css: wider.css
---    


```{r}
#| label: setup

source(here::here("setup.R"))
source(here::here("plan_name.R"))

```

# Tests

## Test whether necessary sheets are included

```{r}
#| label: sheets-tests

results <- testthat::test_file(
  "tests/testthat/test-sheets.R",
  reporter = testthat::TapReporter$new()
)

```

## Test benefit-multiplier rules and function

```{r}
#| label: benefit-multiplier-tests
#| echo: true

test_results <- testthat::test_file(
  "tests/testthat/test-benefit-multiplier.R",
  reporter = TapReporter$new()
)

# test_results |>
#   as_tibble() |>
#   filter(failed > 0)

# Extract all test expectations
# all_expectations <- unlist(lapply(test_results$results, function(x) x))

# # Find failed expectations
# failures <- Filter(function(x) inherits(x, "expectation_failure"), all_expectations)

# if (length(failures) > 0 {
#   waldo::compare(failures[[1]]$expected, failures[[1]]$actual)
# }

```
